#toate judetele din Romania - localizare anunt
JUDETE = [
    ('AB', 'Alba'),
    ('AR', 'Arad'),
    ('AG', 'Argeș'),
    ('BC', 'Bacău'),
    ('BH', 'Bihor'),
    ('BN', 'Bistrița-Năsăud'),
    ('BT', 'Botoșani'),
    ('BV', 'Brașov'),
    ('BR', 'Brăila'),
    ('B', 'București'),
    ('BZ', 'Buzău'),
    ('CS', 'Caraș-Severin'),
    ('CL', 'Călărași'),
    ('CJ', 'Cluj'),
    ('CT', 'Constanța'),
    ('CV', 'Covasna'),
    ('DB', 'Dămbobița'),
    ('DJ', 'Dolj'),
    ('GL', 'Galați'),
    ('GR', 'Giurgiu'),
    ('GJ', 'Gorj'),
    ('HR', 'Harghita'),
    ('HD', 'Hunedoara'),
    ('IL', 'Ialomița'),
    ('IS', 'Iași'),
    ('IF', 'Ilfov'),
    ('MM', 'Maramureș'),
    ('MH', 'Mehedinți'),
    ('MS', 'Mureș'),
    ('NT', 'Neamt'),
    ('OT', 'Olt'),
    ('PH', 'Prahova'),
    ('SM', 'Sata Mare'),
    ('SJ', 'Sălaj'),
    ('SB', 'Sibiu'),
    ('SV', 'Suceava'),
    ('TR', 'Teleorman'),
    ('TM', 'Timiș'),
    ('TL', 'Tulcea'),
    ('VS', 'Vaslui'),
    ('VL', 'Vâlcea'),
    ('VN', 'Vrancea'),    
]